"2021-03-13 17:18:14,634 - api_utils.py[line:78] - INFO: local api request: http://127.0.0.1:9380/v1/schedule/202103131718076872491/upload_0/202103131718076872491_upload_0/local/0/status"
"2021-03-13 17:18:14,757 - api_utils.py[line:81] - INFO: {"retcode":0,"retmsg":"success"}
"
"2021-03-13 17:18:14,757 - api_utils.py[line:83] - INFO: local api response: /v1/schedule/202103131718076872491/upload_0/202103131718076872491_upload_0/local/0/status {'retcode': 0, 'retmsg': 'success'}"
"2021-03-13 17:18:14,757 - task_executor.py[line:120] - INFO: run 202103131718076872491 upload_0 202103131718076872491_upload_0 local 0 task"
"2021-03-13 17:18:14,758 - task_executor.py[line:121] - INFO: {'UploadParam': {'file': 'examples/data/default_credit_homo_guest.csv', 'head': 1, 'partition': 10, 'namespace': 'default_credit_homo_guest_guest', 'table_name': 'default_credit_homo_guest', 'work_mode': 0, 'in_version': None}, 'initiator': {'role': 'local', 'party_id': 0}, 'job_parameters': {'work_mode': 0, 'model_id': 'local-0#model', 'model_version': '202103131718076872491'}, 'role': {'local': [0]}, 'local': {'role': 'local', 'party_id': 0}, 'CodePath': 'fate_flow/utils/upload.py/Upload', 'module': 'Upload'}"
"2021-03-13 17:18:14,758 - task_executor.py[line:122] - INFO: {}"
"2021-03-13 17:18:14,998 - tracking.py[line:303] - INFO: save local 0 job: {'f_progress': 100.0}"
"2021-03-13 17:18:15,692 - profile_util.py[line:33] - DEBUG: upload.py:105 call count, takes 0.0037391185760498047s"
"2021-03-13 17:18:15,700 - profile_util.py[line:33] - DEBUG: upload.py:109 call count, takes 0.0005280971527099609s"
"2021-03-13 17:18:15,700 - tracking.py[line:69] - INFO: request save job 202103131718076872491 component upload_0 on local 0 upload data_access metric data"
"2021-03-13 17:18:15,701 - api_utils.py[line:78] - INFO: local api request: http://127.0.0.1:9380/v1/tracking/202103131718076872491/upload_0/202103131718076872491_upload_0/local/0/metric_data/save"
"2021-03-13 17:18:15,712 - api_utils.py[line:81] - INFO: {"retcode":0,"retmsg":"success"}
"
"2021-03-13 17:18:15,712 - api_utils.py[line:83] - INFO: local api response: /v1/tracking/202103131718076872491/upload_0/202103131718076872491_upload_0/local/0/metric_data/save {'retcode': 0, 'retmsg': 'success'}"
"2021-03-13 17:18:15,712 - tracking.py[line:120] - INFO: request save job 202103131718076872491 component upload_0 on local 0 upload data_access metric meta"
"2021-03-13 17:18:15,712 - api_utils.py[line:78] - INFO: local api request: http://127.0.0.1:9380/v1/tracking/202103131718076872491/upload_0/202103131718076872491_upload_0/local/0/metric_meta/save"
"2021-03-13 17:18:15,759 - api_utils.py[line:81] - INFO: {"retcode":0,"retmsg":"success"}
"
"2021-03-13 17:18:15,768 - api_utils.py[line:83] - INFO: local api response: /v1/tracking/202103131718076872491/upload_0/202103131718076872491_upload_0/local/0/metric_meta/save {'retcode': 0, 'retmsg': 'success'}"
"2021-03-13 17:18:15,774 - profile_util.py[line:33] - DEBUG: upload.py:110 call count, takes 0.0035371780395507812s"
"2021-03-13 17:18:15,775 - upload.py[line:65] - INFO: ------------load data finish!-----------------"
"2021-03-13 17:18:15,781 - upload.py[line:66] - INFO: file: /Users/clz/PycharmProjects/standalone-fate-master-1.2.0/examples/data/default_credit_homo_guest.csv"
"2021-03-13 17:18:15,783 - upload.py[line:67] - INFO: total data_count: 12000"
"2021-03-13 17:18:15,784 - upload.py[line:68] - INFO: table name: default_credit_homo_guest, table namespace: default_credit_homo_guest_guest"
"2021-03-13 17:18:15,868 - api_utils.py[line:78] - INFO: local api request: http://127.0.0.1:9380/v1/schedule/202103131718076872491/upload_0/202103131718076872491_upload_0/local/0/status"
"2021-03-13 17:18:15,880 - api_utils.py[line:81] - INFO: {"retcode":0,"retmsg":"success"}
"
"2021-03-13 17:18:15,880 - api_utils.py[line:83] - INFO: local api response: /v1/schedule/202103131718076872491/upload_0/202103131718076872491_upload_0/local/0/status {'retcode': 0, 'retmsg': 'success'}"
"2021-03-13 17:18:15,881 - task_executor.py[line:150] - INFO: finish 202103131718076872491 upload_0 202103131718076872491_upload_0 local 0 success task"
"2021-03-13 17:18:16,337 - job_utils.py[line:348] - INFO: try to stop process pid:82264"
